#ventas
print("ventas")
a=int(input("ingresa los datos de la primera ventaA:"))
b=int(input("ingresa los datos de la segunda ventaB:"))
c=int(input("ingresa los datos de la tercera ventaC:"))

print("Las ventas del producto A son las más elevadas")
if (a>b) or (a>c):
    print("la venta A es la mas Elevada")


print("Ningún producto tiene unas ventas inferiores a 200")

    

      

    